### ISSUE TITLE
Will development on OpenRC continue?

### ISSUE THREAD

**Issue by berberman** [OpenFTC/OpenFTC-app-turbo#16]
> **\<RS9> Software Modification** - Teams are not allowed to modify the FIRST Tech Challenge Driver Station application or Robot Controller SDK in any fashion.

According to *FIRST® Tech Challenge Game Manual Part 1 - Rover Ruckus*.

Guys, will you stick to development.... 😕 

@NoahAndrews  @magneticflux-

**Comment by magneticflux-** [comment]
That's already been discussed privately among the developers. ModularFTC will continue development and maintenance for practice use. I can't make claims about OpenFTC.

**Comment by ItsHarper** [comment]
By my interpretation of last year's ruling, OpenRC's stock mode (which doesn't modify the precompiled libraries) was legal for competition use. The new rule this year needs a forum clarification IMO. Regardless of legality, OpenRC will continue to be maintained this season. At the very least, it is useful for pointing to parts of the SDK's source code, and for having a public (though very course) git history, which will allow people to see the SDK evolving over time.

See this issue for what I have to say on when OpenRC will be updated: https://github.com/OpenFTC/OpenRC/issues/79
