### ISSUE TITLE
Benchmarking notes

### ISSUE THREAD

**Issue by ItsHarper** [OpenFTC/OpenFTC-app-turbo#2]
- Test with D8 compiler on and off (requires Android Studio 3)
 - Tests should be conducted with the computer connected to the RC phone's network

**Comment by magneticflux-** [comment]
What sort of improvement in size do you expect to see with these libraries removed? Do you have a MB delta handy?

**Comment by ItsHarper** [comment]
The Turbo app is currently about 8 MB, version 3.4 of the official app is about 33 MB, and version 3.5 of the official app is about 19 MB. So we're still less than half the size of the official app, even after they trimmed down the largest file for OnBotJava.

**Comment by magneticflux-** [comment]
@NoahAndrews Okay, that's on par with my own results [here](https://modular-ftc.github.io/). Additionally, I've found that OpenCV adds about 4MB from all the native libraries included.

Additionally, Kotlin adds a negligible amount to the `apk` and using the D8 compiler saves about 100KB.

**Comment by ItsHarper** [comment]
Add a side-by-side gif to the Readme

**Comment by Windwoes** [comment]
You added benchmarks to the website, so I'm closing this...

**Comment by ItsHarper** [comment]
Reopening. I didn't do any tests with D8, didn't compare against the official SDK, didn't make a gif.
