### ISSUE TITLE
Calling OnBotJava and Blocks bloat is a bit insulting to the FTC Tech Team 

### ISSUE THREAD

**Issue by lizlooney** [OpenFTC/OpenFTC-app-turbo#4]
Can you change "FTC robot controller app - minus the OnBotJava and Blocks bloat!" to "FTC robot controller app - minus the OnBotJava and Blocks."?

Thanks!

**Comment by ItsHarper** [comment]
Hi Liz, I'm truly sorry to have offended you. I know you put a lot of effort into helping integrate Blockly into the FTC app. 

By "bloat" I meant "features that waste a lot of resources if you don't need them", not that the features themselves are useless. One of the teams I mentor is using the Blocks programming, and we're enjoying using it. Thank you! :) I definitely understand the usefulness of OnBotJava as well. Android Studio can be a hassle to set up, and the lower FIRST can get the barrier to entry, the better.

I'll make sure to change the description tonight. I'm sorry for the inappropriate implication of the current version.

**Comment by lizlooney** [comment]
Thanks for updating the description! And thanks for your nice comments about using Blocks with the team you mentor.
